"""create package_types and packages

Revision ID: 91edec99dfaa
Revises:
Create Date: 2025-11-25 23:10:33.387167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91edec99dfaa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column(
            "content_price_usd", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "delivery_price_rub", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column("delivery_calculated", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["package_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_packages_company_id"), "packages", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_packages_delivery_calculated"),
        "packages",
        ["delivery_calculated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_packages_delivery_price_rub"),
        "packages",
        ["delivery_price_rub"],
        unique=False,
    )
    op.create_index(
        op.f("ix_packages_session_id"), "packages", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_packages_type_id"), "packages", ["type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packages_type_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_session_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_delivery_price_rub"), table_name="packages")
    op.drop_index(op.f("ix_packages_delivery_calculated"), table_name="packages")
    op.drop_index(op.f("ix_packages_company_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_table("package_types")
    # ### end Alembic commands ###
